In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('/Users/lerapasko/Downloads/developer-survey-2025.csv')
df.head()

/var/folders/t7/7lbzcymx7bq60pd65tsk3mb40000gn/T/ipykernel_57673/3111272297.py:1: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/lerapasko/Downloads/developer-survey-2025.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [6]:
total_respondents = len(df)
print("Загальна кількість респондентів:", total_respondents)

Загальна кількість респондентів: 49191

In [10]:
schema = pd.read_csv('/Users/lerapasko/Downloads/schema.csv')
schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [14]:
# Отримуємо список питань з колонки qname
schema_questions = set(schema["qname"])

# Отримуємо список колонок основного датасету
df_columns = set(df.columns)

# Інтерсекція множин
existing_questions = schema_questions.intersection(df_columns)

# Фільтруємо тільки потрібні колонки
filtered_df = df[list(existing_questions)]

# Знаходимо респондентів без пропущених значень
complete_respondents = filtered_df.notna().all(axis=1)

# Підрахунок кількості таких респондентів
total_complete = complete_respondents.sum()

print("Кількість респондентів, які відповіли на всі питання:")
print(total_complete)

Кількість респондентів, які відповіли на всі питання:
0

In [38]:
# Вибираємо колонку WorkExp
work_exp = df["WorkExp"]

# Обчислення мір центральної тенденціїб, даний спосіб ігнорує NaN значення 
mean_value = work_exp.mean()
median_value = work_exp.median()
mode_value = work_exp.mode()[0]

# Формуємо результати у вигляді Series
central_tendency = pd.Series({
    "Mean": round(mean_value, 3),
    "Median": round(median_value, 3),
    "Mode": round(mode_value, 3)
})

print("Міри центральної тенденції для WorkExp:")
print(central_tendency)

Міри центральної тенденції для WorkExp:
Mean      13.367
Median    10.000
Mode      10.000
dtype: float64

In [39]:
# Шукаємо колонки, де зустрічається значення "Remote"
for col in df.columns:
    if df[col].astype(str).str.contains("Remote", case=False, na=False).any():
        print(col)

RemoteWork
TechOppose_15_TEXT
JobSatPoints_15_TEXT
DatabaseHaveEntry
AIExplain
AIOpen

In [40]:
# Перевіряємо унікальні значення
print(df["RemoteWork"].unique())

<StringArray>
[                                                                      'Remote',
                          'Hybrid (some in-person, leans heavy to flexibility)',
                                                                            nan,
                                                                    'In-person',
                               'Hybrid (some remote, leans heavy to in-person)',
 'Your choice (very flexible, you can come in when you want or just as needed)']
Length: 6, dtype: str

In [41]:
# Кількість респондентів, які працюють віддалено
remote_count = len(df[df["RemoteWork"] == "Remote"])

print("Кількість респондентів, які працюють віддалено:")
print(remote_count)

Кількість респондентів, які працюють віддалено:
10931

In [42]:
# Шукаємо колонки, де зустрічається значення "Python"
for col in df.columns:
    if df[col].astype(str).str.contains("Python", case=False, na=False).any():
        print(col)

TechEndorse_13_TEXT
TechOppose_15_TEXT
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
LanguagesHaveEntry
LanguagesWantEntry
DatabaseHaveEntry
PlatformHaveEntry
PlatformWantEntry
WebframeHaveEntry
WebframeWantEntry
DevEnvHaveEntry
DevEnvWantEntry
SOTagsHaveEntry
SOTagsWant Entry
OfficeStackHaveEntry
OfficeStackWantEntry
CommPlatformHaveEntr
CommPlatformWantEntr
AIExplain
AIAgentKnowWrite
AIAgentExtWrite
AIOpen

In [43]:
df["LanguageHaveWorkedWith"].head()

0                     Bash/Shell (all shells);Dart;SQL
1                                                 Java
2                  Dart;HTML/CSS;JavaScript;TypeScript
3                                      Java;Kotlin;SQL
4    C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
Name: LanguageHaveWorkedWith, dtype: str

In [44]:
# Знаходимо респондентів, які використовують Python
python_users = df["LanguageHaveWorkedWith"].str.contains("Python",case=False,na=False)

# Обчислюємо відсоток
python_percentage = python_users.mean() * 100

# Виводимо результат
print(f"Відсоток респондентів, які програмують на Python: {python_percentage:.2f}%")

Відсоток респондентів, які програмують на Python: 37.54%

In [50]:
# Шукаємо колонки, пов’язані з навчанням
for col in df.columns:
    if "learn" in col.lower() or "education" in col.lower():
        print(col)

LearnCodeChoose
LearnCode
LearnCodeAI
AILearnHow

In [51]:
df["LearnCode"].head()

0    Online Courses or Certification (includes all ...
1    Online Courses or Certification (includes all ...
2    Online Courses or Certification (includes all ...
3    Other online resources (e.g. standard search, ...
4                                                  NaN
Name: LearnCode, dtype: str

In [52]:
# Знаходимо респондентів, які вчились онлайн
online_courses = df["LearnCode"].str.contains("Online",case=False,na=False)

total_online = online_courses.sum()

print("Кількість респондентів, які навчалися через онлайн курси:")
print(total_online)

Кількість респондентів, які навчалися через онлайн курси:
28352

In [55]:
# Фільтруємо респондентів, які програмують на Python
python_devs = df[df["LanguageHaveWorkedWith"].str.contains( "Python", case=False, na=False)]

# Видаляємо рядки з пропущеною компенсацією або країною
python_devs = python_devs.dropna(
    subset=["Country", "ConvertedCompYearly"]
)

# Групування по країнах та обчислення стати
compensation_stats = (
    python_devs
    .groupby("Country")["ConvertedCompYearly"]
    .agg(
        MeanCompensation="mean",
        MedianCompensation="median"
    )
    .reset_index()
)

display(compensation_stats)

,Country,MeanCompensation,MedianCompensation
0,Afghanistan,22328.666667,1000.0
1,Albania,47217.600000,50000.0
2,Algeria,20187.285714,7088.0
3,Andorra,226103.500000,226103.5
4,Antigua and Barbuda,1.000000,1.0
...,...,...,...
148,"Venezuela, Bolivarian Republic of...",9908.647059,3000.0
149,Viet Nam,218837.166667,8254.0
150,Yemen,32929.500000,23672.0
151,Zambia,5424.250000,3206.0
152,Zimbabwe,34000.000000,25500.0

In [58]:
# Видаляємо рядки з пропущеними значеннями
top_paid = df.dropna(subset=["ConvertedCompYearly", "EdLevel"])

# Сортуємо за компенсацією у спадному порядку
top_paid = top_paid.sort_values(by="ConvertedCompYearly",ascending=False)

# Обираємо топ-5 респондентів
top_5 = top_paid.head(5)

result = top_5[["ConvertedCompYearly", "EdLevel"]]

display(result)

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

In [59]:
# Створюємо колонку з інформацією,чи використовує респондент Python
df["UsesPython"] = df["LanguageHaveWorkedWith"].str.contains("Python", case=False,na=False)

# Видаляємо рядки без вікової категорії
age_data = df.dropna(subset=["Age"])

# Групуємо за віковими категоріями
python_by_age = (
    age_data
    .groupby("Age")
    .agg(
        PythonPercent=("UsesPython", lambda x: x.mean() * 100)
    )
    .reset_index()
)

# Перейменовуємо колонки
python_by_age.columns = ["AgeCategory","PythonDevelopersPercent"]

# Округлюємо значення
python_by_age["PythonDevelopersPercent"] = (
    python_by_age["PythonDevelopersPercent"]
    .round(2)
)

# Виводимо результат
display(python_by_age)

         AgeCategory  PythonDevelopersPercent
0    18-24 years old                    40.00
1    25-34 years old                    36.94
2    35-44 years old                    36.72
3    45-54 years old                    38.63
4    55-64 years old                    37.24
5  65 years or older                    31.63
6  Prefer not to say                    31.22